POST http://localhost:3004/register
Content-Type:application/json

{
  "Name":"SampathK", 
  "Email":"student1234@gmail.com", 
  "PhoneNo":"9876543211",
  "Profession":"Dcotor", 
  "password":"test2@gmail.com", 
  "cPassword":"test2@gmail.com"
} 
### 

POST http://localhost:3006/login
Content-Type:application/json 

{
  "Email":"test123@gmail.com", 
  "password":"abcd@12"
}

### 

GET http://localhost:3006/about 

